#!/bin/bash
clear
for FELHASZNALONEV in `cat jelszocsere_diak.csv`; do

JELSZO=`pwgen -B -s 8 1 -1 -0 -c -v`
samba-tool user setpassword $FELHASZNALONEV --newpassword=$JELSZO

echo "$FELHASZNALONEV;$JELSZO" >> diak_jelszavak.txt

(
echo "Kedves Diákunk!"
echo ""
echo "Számítógépekhez és a wifi-hez használt jelszavad megváltozott."
echo ""
echo "Felhasználói név: $FELHASZNALONEV"
echo "Új jelszó: $JELSZO"
echo ""
echo "Üdvözlettel:"
echo "rendszergazda"

) | mail -s "[CRNL] Új Windows jelszó" $FELHASZNALONEV@diak.crnl.hu 

sleep 5

done