#!/bin/bash
clear

for FELHASZNALONEV in `cat jelszocsere_tanar.csv`; do

JELSZO=`pwgen -B -s 8 1 -1 -0 -c -v`
samba-tool user setpassword $FELHASZNALONEV --newpassword=$JELSZO

echo "$FELHASZNALONEV;$JELSZO" >> tanar_jelszavak.txt

(
echo "Kedves Kolléga!"
echo ""
echo "Számítógépekhez, valamint a WIFI-hez használt jelszavad megváltozott."
echo ""
echo "Felhasználói név: $FELHASZNALONEV"
echo "Új jelszó: $JELSZO"
echo ""
echo "Üdvözlettel:"
echo "Szabolcs"

)  | mail -s "[CRNL] Új Windows jelszó" $FELHASZNALONEV@crnl.hu

sleep 5

done