#!/bin/bash
IFS=,
while read group username password surname givenname
      do
    if [ `samba-tool group list | grep "$group" | wc -l` = 1 ]; then
#	JELSZO=`pwgen 8 1`
	JELSZO=$password
	samba-tool user create --must-change-at-next-login --script-path="stuff.cmd" --surname="$surname" --given-name="$givenname" --mail-address="$username@domain.com" $username $JELSZO
	samba-tool group addmembers stuff $username;
	samba-tool user move $username "ou=Stuff,ou=Dolgozók"
	mkdir -p /share/home/dolgozok/$username; chmod -R 777 /share/home/dolgozok/$username;
	echo "$group,$username,$JELSZO" >> /home/$USER/new-worker.csv
    fi
done < $1
