#!/bin/bash
clear
echo "Melyik osztály? (pl.: 2024-7A)"
read OSZTALY
samba-tool group listmembers $OSZTALY | sort
echo "Felhasználói név?"
read FELHASZNALONEV

JELSZO=`pwgen -B -s 8 1 -1 -0 -c -v`
samba-tool user setpassword $FELHASZNALONEV --newpassword=$JELSZO
(
echo "Subject: [CNK] Új Windows jelszó"
echo "From: noreply@cnkpecs.hu"
echo ""
echo "Kedves Diákunk!"
echo ""
echo "Számítógépekhez használt jelszavad megváltozott."
echo ""
echo "Felhasználói név: $FELHASZNALONEV"
echo "Új jelszó: $JELSZO"
echo ""
echo "Üdvözlettel:"
echo "rendszergazda"

) | msmtp $FELHASZNALONEV@diak.cnkpecs.hu

