#!/bin/bash
clear
echo "Melyik osztály? (pl.: 2024-07A)"
read OSZTALY
samba-tool group listmembers $OSZTALY | sort
echo "Felhasználói név?"
read FELHASZNALONEV
samba-tool user setpassword $FELHASZNALONEV
